### ISSUE TITLE
macos can not use

### ISSUE THREAD

**Issue by chenlinhsfl** [datvm/JsPermissionHandler#1]
i clone the git,it's can't use in macos
![6c6667be2ab465cdf19c585c7c7c942](https://github.com/datvm/JsPermissionHandler/assets/24708970/74814de0-5d10-4ce4-9a5f-b7078aa0f6b9)

**Comment by datvm** [comment]
@chenlinhsfl hi, it is not working for Mac Catalyst. It's a bug from Apple. See https://github.com/dotnet/maui/issues/20511

**Comment by chenlinhsfl** [comment]
Are there any alternatives？and do you know the future repair plan

**Comment by datvm** [comment]
@chenlinhsfl not until Apple fixes that. There is nothing we can do from Blazor side. You can stream the video from native but that's a whole different thing. This is for MAUI **Blazor** (WebView UI)
